name: Merge Upstream AI

on:
  schedule:
    - cron: '0 0/8 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dashboard  # 切换到你的目标分支
          token: ${{ secrets.GITHUB_TOKEN }}  # 或你的个人访问令牌

      - name: Add upstream remote
        run: |
          git remote add -f upstream "https://github.com/LmeSzinc/AzurLaneAutoScript.git"

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Configure Git user  # 新增：配置提交者身份
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"

      - name: Abort previous conflicting operations  # 新增：清理冲突状态
        run: |
          git merge --abort || true
          git rebase --abort || true

      - name: Merge upstream into local branch (with --no-ff)
        run: |
          git merge upstream/master --no-ff --allow-unrelated-histories -m "Merge upstream/master into dashboard"
        # 如果合并失败（有冲突），可以尝试变基
        continue-on-error: true

      - name: Resolve conflicts with rebase (如果合并失败)
        run: |
          git rebase upstream/master
        continue-on-error: true

      - name: Resolve conflicts with theirs strategy
        run: |
          git merge -s ours upstream/master -m "Merge upstream with theirs strategy"
        continue-on-error: true

      - name: Push changes to origin
        run: |
          git push origin dashboard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
